--------------------------------------------------------
--  File created - Friday-August-09-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PLAYER_STATISTICS_PIVOT
--------------------------------------------------------

  CREATE TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" 
   ("YEAR_ID" NUMBER(38,0), 
	"YEAR_NM" NUMBER(38,0), 
	"TEAM_ID" NUMBER(38,0), 
	"TEAM_NM" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"DIVISION" NUMBER(38,0), 
	"NUM_PLAYERS" NUMBER(38,0), 
	"JERSEY_01" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_01" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_01" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_01" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_01" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_01" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_01" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_01" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_01" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_01" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_01" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_02" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_02" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_02" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_02" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_02" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_02" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_02" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_02" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_02" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_02" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_02" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_03" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_03" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_03" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_03" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_03" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_03" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_03" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_03" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_03" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_03" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_03" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_04" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_04" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_04" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_04" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_04" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_04" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_04" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_04" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_04" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_04" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_04" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_05" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_05" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_05" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_05" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_05" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_05" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_05" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_05" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_05" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_05" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_05" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_06" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_06" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_06" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_06" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_06" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_06" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_06" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_06" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_06" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_06" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_06" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_07" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_07" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_07" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_07" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_07" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_07" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_07" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_07" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_07" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_07" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_07" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_08" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_08" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_08" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_08" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_08" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_08" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_08" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_08" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_08" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_08" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_08" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_09" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_09" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_09" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_09" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_09" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_09" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_09" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_09" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_09" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_09" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_09" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_10" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_10" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_10" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_10" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_10" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_10" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_10" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_10" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_10" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_10" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_10" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_11" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_11" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_11" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_11" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_11" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_11" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_11" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_11" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_11" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_11" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_11" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_12" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_12" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_12" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_12" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_12" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_12" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_12" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_12" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_12" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_12" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_12" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_13" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_13" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_13" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_13" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_13" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_13" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_13" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_13" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_13" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_13" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_13" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_14" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_14" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_14" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_14" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_14" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_14" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_14" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_14" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_14" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_14" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_14" NUMBER(38,0) DEFAULT ON NULL 0, 
	"JERSEY_15" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"PLAYER_15" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"YEAR_15" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"POSITION_15" VARCHAR2(26 BYTE) COLLATE "USING_NLS_COMP", 
	"HEIGHT_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_PLAYED_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_STARTED_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"GAMES_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"MINUTES_PLAYED_15" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOALS_MADE_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOALS_ATTEMPTED_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PERCENT_15" NUMBER(38,2) DEFAULT ON NULL 0, 
	"THREE_POINT_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_ATTEMPT_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_POINT_PERCENT_15" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FREE_THROW_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_ATTEMPT_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PERCENT_15" NUMBER(38,2) DEFAULT ON NULL 0, 
	"POINTS_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_15" NUMBER(38,2) DEFAULT ON NULL 0, 
	"OFFENSIVE_REBOUNDS_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DEFENSIVE_REBOUNDS_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TOTAL_REBOUNDS_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"AVERAGE_REBOUNDS_15" NUMBER(38,2) DEFAULT ON NULL 0, 
	"ASSISTS_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURN_OVERS_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FOULS_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DOUBLE_DOUBLE_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TRIPLE_DOUBLE_15" NUMBER(38,0) DEFAULT ON NULL 0, 
	"DISQUALIFY_15" NUMBER(38,0) DEFAULT ON NULL 0
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table PLAYER_STATISTICS_PIVOT
--------------------------------------------------------

  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_01" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_02" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_03" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_04" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_05" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_06" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_07" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_08" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_09" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_10" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_11" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_12" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_13" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_14" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("HEIGHT_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_PLAYED_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_STARTED_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("GAMES_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("MINUTES_PLAYED_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_MADE_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOALS_ATTEMPTED_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FIELD_GOAL_PERCENT_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_ATTEMPT_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("THREE_POINT_PERCENT_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_ATTEMPT_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FREE_THROW_PERCENT_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("POINTS_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("OFFENSIVE_REBOUNDS_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DEFENSIVE_REBOUNDS_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TOTAL_REBOUNDS_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("AVERAGE_REBOUNDS_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("ASSISTS_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TURN_OVERS_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("STEALS_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("BLOCKED_SHOTS_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("FOULS_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DOUBLE_DOUBLE_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("TRIPLE_DOUBLE_15" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."PLAYER_STATISTICS_PIVOT" MODIFY ("DISQUALIFY_15" NOT NULL ENABLE);
