--------------------------------------------------------
--  File created - Friday-August-09-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TEAM_STATISTICS
--------------------------------------------------------

  CREATE TABLE "RWBSTATS"."TEAM_STATISTICS" 
   ("YEAR_ID" NUMBER(38,0), 
	"YEAR_NM" NUMBER(38,0), 
	"TEAM_ID" NUMBER(38,0), 
	"TEAM_NM" VARCHAR2(128 BYTE) COLLATE "USING_NLS_COMP", 
	"DIVISION" NUMBER(38,0), 
	"SCORING_OFFENSE_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"SCORING_OFFENSE_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"SCORING_DEFENCE_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"SCORING_DEFENCE_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"SCORING_MARGIN_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"SCORING_MARGIN_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"REBOUND_MARGIN_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"REBOUND_MARGIN_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"ASSISTS_PER_GAME_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"ASSISTS_PER_GAME_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_PER_GAME_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"BLOCKED_SHOTS_PER_GAME_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"STEALS_PER_GAME_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"STEALS_PER_GAME_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"TURNOVER_MARGIN_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"TURNOVER_MARGIN_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"ASSIST_TURNOVER_RATIO_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"ASSIST_TURNOVER_RATIO_VALUE" NUMBER(38,2) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PER_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PER_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PER_DEFENSE_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FIELD_GOAL_PER_DEFENSE_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"THREE_PT_FIELD_GOALS_PER_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_PT_FIELD_GOALS_PER_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"THREE_PT_FIELD_GOAL_PER_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"THREE_PT_FIELD_GOAL_PER_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"FREE_THROW_PER_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"FREE_THROW_PER_VALUE" NUMBER(38,1) DEFAULT ON NULL 0, 
	"WON_LOST_PER_RANK" NUMBER(38,0) DEFAULT ON NULL 0, 
	"WON_LOST_PER_VALUE" NUMBER(38,1) DEFAULT ON NULL 0
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table TEAM_STATISTICS
--------------------------------------------------------

  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("SCORING_OFFENSE_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("SCORING_OFFENSE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("SCORING_DEFENCE_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("SCORING_DEFENCE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("SCORING_MARGIN_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("SCORING_MARGIN_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("REBOUND_MARGIN_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("REBOUND_MARGIN_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("ASSISTS_PER_GAME_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("ASSISTS_PER_GAME_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("BLOCKED_SHOTS_PER_GAME_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("BLOCKED_SHOTS_PER_GAME_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("STEALS_PER_GAME_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("STEALS_PER_GAME_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("TURNOVER_MARGIN_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("TURNOVER_MARGIN_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("ASSIST_TURNOVER_RATIO_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("ASSIST_TURNOVER_RATIO_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("FIELD_GOAL_PER_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("FIELD_GOAL_PER_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("FIELD_GOAL_PER_DEFENSE_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("FIELD_GOAL_PER_DEFENSE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("THREE_PT_FIELD_GOALS_PER_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("THREE_PT_FIELD_GOALS_PER_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("THREE_PT_FIELD_GOAL_PER_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("THREE_PT_FIELD_GOAL_PER_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("FREE_THROW_PER_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("FREE_THROW_PER_VALUE" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("WON_LOST_PER_RANK" NOT NULL ENABLE);
  ALTER TABLE "RWBSTATS"."TEAM_STATISTICS" MODIFY ("WON_LOST_PER_VALUE" NOT NULL ENABLE);
